description: Heat Template - Networking - Individual for Students
heat_template_version: '2017-09-01'
parameters:
  last_name:
    constraints:
    - description: Last name must be no longer than 15 characters
      length: {max: 15, min: 1}
    - {allowed_pattern: '[a-zA-Z]*', description: Last name may only contain letters}
    default: null
    description: Last Name
    label: Last Name
    type: string
  password:
    constraints:
    - description: Password must be between 8 and 20 characters
      length: {max: 20, min: 8}
    - {allowed_pattern: '[a-zA-Z0-9]*', description: Password may not contain special
        characters}
    default: password
    description: Set root/admin password for instances
    hidden: true
    label: Password
    type: string
resources:

  network_0:
    properties: {admin_state_up: true, name: Net0, shared: false}
    type: OS::Neutron::Net
  network_1:
    properties: {admin_state_up: true, name: Net1, shared: false}
    type: OS::Neutron::Net
  network_2:
    properties: {admin_state_up: true, name: Net2, shared: false}
    type: OS::Neutron::Net
  network_3:
    properties: {admin_state_up: true, name: Net3, shared: false}
    type: OS::Neutron::Net

  subnet_0:
    properties:
      allocation_pools:
      - {end: 10.0.0.250, start: 10.0.0.100}
      cidr: 10.0.0.0/24
      dns_nameservers: [10.50.255.254]
      enable_dhcp: true
      gateway_ip: 10.0.0.254
      host_routes: []
      ip_version: 4
      name: subnet0
      network_id: {get_resource: network_0}
    type: OS::Neutron::Subnet
  subnet_1:
    properties:
      allocation_pools:
      - {end: 10.1.0.250, start: 10.1.0.100}
      cidr: 10.1.0.0/24
      dns_nameservers: [10.50.255.254]
      enable_dhcp: true
      gateway_ip: 10.1.0.254
      host_routes:
      - {destination: 10.1.0.0/24, nexthop: 10.1.0.1}
      - {destination: 10.2.0.0/24, nexthop: 10.1.0.1}
      - {destination: 10.3.0.0/24, nexthop: 10.1.0.1}
      ip_version: 4
      name: subnet1
      network_id: {get_resource: network_1}
    type: OS::Neutron::Subnet
  subnet_2:
    properties:
      allocation_pools:
      - {end: 10.2.0.250, start: 10.2.0.100}
      cidr: 10.2.0.0/24
      dns_nameservers: [10.50.255.254]
      enable_dhcp: true
      gateway_ip: 10.2.0.254
      host_routes:
      - {destination: 10.1.0.0/24, nexthop: 10.2.0.1}
      - {destination: 10.2.0.0/24, nexthop: 10.2.0.1}
      - {destination: 10.3.0.0/24, nexthop: 10.2.0.1}
      ip_version: 4
      name: subnet2
      network_id: {get_resource: network_2}
    type: OS::Neutron::Subnet
  subnet_3:
    properties:
      allocation_pools:
      - {end: 10.3.0.250, start: 10.3.0.100}
      cidr: 10.3.0.0/24
      dns_nameservers: [10.50.255.254]
      enable_dhcp: true
      gateway_ip: 10.3.0.254
      host_routes:
      - {destination: 10.1.0.0/24, nexthop: 10.3.0.1}
      - {destination: 10.2.0.0/24, nexthop: 10.3.0.1}
      - {destination: 10.3.0.0/24, nexthop: 10.3.0.1}
      ip_version: 4
      name: subnet3
      network_id: {get_resource: network_3}
    type: OS::Neutron::Subnet

  external_router:
    properties:
      external_gateway_info: {network: public}
      name: external_router
    type: OS::Neutron::Router
  external_router_interface_0:
    properties:
      router_id: {get_resource: external_router}
      subnet_id: {get_resource: subnet_0}
    type: OS::Neutron::RouterInterface
  external_router_interface_1:
    properties:
      router_id: {get_resource: external_router}
      subnet_id: {get_resource: subnet_1}
    type: OS::Neutron::RouterInterface
  external_router_interface_2:
    properties:
      router_id: {get_resource: external_router}
      subnet_id: {get_resource: subnet_2}
    type: OS::Neutron::RouterInterface
  external_router_interface_3:
    properties:
      router_id: {get_resource: external_router}
      subnet_id: {get_resource: subnet_3}
    type: OS::Neutron::RouterInterface

# --- Start Firewall virtual machine

  firewall1_subnet_0_port:
    properties:
      fixed_ips:
      - {ip_address: 10.0.0.1}
      network_id: {get_resource: network_0}
      port_security_enabled: false
    type: OS::Neutron::Port
  firewall1_subnet_1_port:
    properties:
      fixed_ips:
      - {ip_address: 10.1.0.1}
      network_id: {get_resource: network_1}
      port_security_enabled: false
    type: OS::Neutron::Port
  firewall1_subnet_2_port:
    properties:
      fixed_ips:
      - {ip_address: 10.2.0.1}
      network_id: {get_resource: network_2}
      port_security_enabled: false
    type: OS::Neutron::Port
  firewall1_subnet_3_port:
    properties:
      fixed_ips:
      - {ip_address: 10.3.0.1}
      network_id: {get_resource: network_3}
      port_security_enabled: false
    type: OS::Neutron::Port
  firewall1:
    properties:
      diskConfig: AUTO
      flavor: cy.medium
      image: pfSense
      name: net-Firewall
      networks:
      - port: {get_resource: firewall1_subnet_0_port}
      - port: {get_resource: firewall1_subnet_1_port}
      - port: {get_resource: firewall1_subnet_2_port}
      - port: {get_resource: firewall1_subnet_3_port}
    type: OS::Nova::Server

# --- Start LAN network virtual machines

  net1_subnet_1_port:
    properties:
      fixed_ips:
      - {ip_address: 10.1.0.2}
      network_id: {get_resource: network_1}
      port_security_enabled: false
    type: OS::Neutron::Port
  float_ip_net1:
    type: OS::Neutron::FloatingIP
    depends_on: external_router
    properties: { floating_network: public }
  float_ip_assoc_net1:
    type: OS::Neutron::FloatingIPAssociation
    depends_on: external_router_interface_1
    properties:
      floatingip_id: { get_resource: float_ip_net1 }
      port_id: { get_resource: net1_subnet_1_port }
  net1:
    properties:
      diskConfig: AUTO
      flavor: cy.medium
      image: Debian LXDE
      name: net1
      networks:
      - port: {get_resource: net1_subnet_1_port}
      user_data:
            str_replace:
              template: { get_file: "https://git.cybbh.space/electric-boogaloo/public/raw/master/modules/networking/heat/packages_and_scripts/net1.sh" }
              params:
                $user: { get_param: last_name }
                $password: { get_param: password }
      user_data_format: RAW
    type: OS::Nova::Server

  net2_subnet_1_port:
    properties:
      fixed_ips:
      - {ip_address: 10.1.0.3}
      network_id: {get_resource: network_1}
      port_security_enabled: false
    type: OS::Neutron::Port
  net2:
    type: OS::Nova::Server
    properties:
      diskConfig: AUTO
      flavor: cy.large
      image: Windows 1803
      name: net2
      networks:
        - port: { get_resource: net2_subnet_1_port }
      user_data:
            str_replace:
              template: { get_file: "https://git.cybbh.space/electric-boogaloo/public/raw/master/modules/networking/heat/packages_and_scripts/win1.ps1" }
              params:
                $user: { get_param: last_name }
                $password: { get_param: password }
      user_data_format: RAW

# --- Start LAN2 network virtual machines

  net3_subnet_2_port:
    properties:
      fixed_ips:
      - {ip_address: 10.2.0.2}
      network_id: {get_resource: network_2}
      port_security_enabled: false
    type: OS::Neutron::Port
  net3:
    type: OS::Nova::Server
    properties:
      name: net3
      image: Ubuntu 16.04
      flavor: cy.medium
      diskConfig: AUTO
      networks:
        - port: { get_resource: net3_subnet_2_port }
      user_data:
            str_replace:
              template: { get_file: "https://git.cybbh.space/electric-boogaloo/public/raw/master/modules/networking/heat/packages_and_scripts/nix1_net3.sh" }
              params:
                $user: { get_param: last_name }
                $password: { get_param: password }
      user_data_format: RAW

  net4_subnet_2_port:
    properties:
      fixed_ips:
      - {ip_address: 10.2.0.3}
      network_id: {get_resource: network_2}
      port_security_enabled: false
    type: OS::Neutron::Port
  net4:
    properties:
      diskConfig: AUTO
      flavor: cy.medium
      image: Ubuntu 14.04
      name: net4
      networks:
      - port: { get_resource: net4_subnet_2_port }
      user_data:
            str_replace:
              template: { get_file: "https://git.cybbh.space/electric-boogaloo/public/raw/master/modules/networking/heat/packages_and_scripts/net4.sh" }
              params:
                $user: { get_param: last_name }
                $password: { get_param: password }
      user_data_format: RAW
    type: OS::Nova::Server

# --- Start DMZ network machines

  DMZ_subnet_3_port:
    properties:
      fixed_ips:
      - {ip_address: 10.3.0.2}
      network_id: {get_resource: network_3}
      port_security_enabled: false
    type: OS::Neutron::Port
  DMZ:
    properties:
      diskConfig: AUTO
      flavor: cy.medium
      image: Debian LXDE
      name: net-DMZ
      networks:
      - port: {get_resource: DMZ_subnet_3_port}
      user_data:
            str_replace:
              template: { get_file: "https://git.cybbh.space/electric-boogaloo/public/raw/master/modules/networking/heat/packages_and_scripts/DMZ.sh" }
              params:
                $user: { get_param: last_name }
                $password: { get_param: password }
      user_data_format: RAW
    type: OS::Nova::Server
